sudo: false
language: python
matrix:
  include:
  - python: 2.7
    env: TOX_ENV=pep8
  - python: 2.7
    env: TOX_ENV=py27
  - python: 3.6
    env: TOX_ENV=py36
install:
- pip install tox
script:
- tox -e $TOX_ENV
deploy:
  provider: pypi
  user: toabctl
  password:
    secure: XU/FV623lG48aBV/CuCgOK2idAcfIjkEJbHGXp76Z2XK1+IdbBuIQZF9Lq0OnGINjYpJ/QvgeycciXW1q3WYniZcMaxOYwfQvuqkfZzehwkQWma0HaCadMkSMaKrHR0TvLNb/nNvYC6jf4A9AHcRDdHW7LOngSSls/WpsFPKTeO5gvwxmwjzotdo14NlJtFxcEdwZtRIhVH2FsvUOWsK0K5X9/137mLA/GQ3rDvkQQ/9d1lLUiGWcsEDeeY1FjsG0Wp2b4b6JpTkqMBe2WTzmnDL1JJ8Q8XyTOpCxoXujvMJQD0NxUyrc3iWzAuiyJ4JIgqqw1w4DtQKrUScwVE+NZaItnE3bAox/QbKU/xjE1WMQ4PBsGMW6ljhDZbNIMWlKuEDGRxKhWOO2kDUfdQhmCzxUfb3FcEf87OLQ8Va5Bv2NUbSBiS6MScTFFeR7wA5ikT63yWE9uEnotlm0kYI33G/PC1TEYhWHFoV/KPdhmTRF0hNiMrYB6Q3pbPa0fqPHlfVKw4W3M+tCyqCCHgyO9mhLou2cnenkaVuqPIH2V/fAhFFkagFndvAe1m4iY1QI3Ir4RtDrZzk+yEZHVCBup47uFh11JA0Li/DK4EfWt+vXqYO4cNRSpBhXG2r+FnF4vly4MIGJ/hjJDY25S3AZ7co/RNn2m5FwH8klGnVfHU=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: toabctl/metaextract
